src/main/java/nl/mpcjanssen/simpletask/AddTask.java

I guess this is a pretty naive change, and I couldn't test it in the emulator in Android studio because of no microphone. This is my first attempt at any android development.

prepend date to ok google messages

---

src/main/res/values-de/strings.xml

Added German translation for Calender Sync

Update of German translation

---

src/main/java/nl/mpcjanssen/simpletask/CalendarSync.java

A couple of minor bugfixes. Also, I made the calendar read-only so that the user doesn't accidentaly create events in it (they would probably get deleted later and the calendar might be deleted too).

Bugfixes in CalendarSync

---

src/main/java/nl/mpcjanssen/simpletask/CalendarSync.java

Calendar sync: Check if reminder is in the future when inserting

---

src/main/res/xml/preferences.xml

text.
Hope this is correct
Regards
Carlo D.

Modified some strings in preferences.xml to reflect the translation

---

src/main/res/values/strings.xml

Add some periods to summaries, and a comma here and there.

Fix some minor punctuation errors

---

src/main/java/nl/mpcjanssen/simpletask/AddTask.java

Trying to solve issue https://github.com/mpcjanssen/simpletask-android/issues/132 .
With this change, the user will have preselected tag and list ListView in the task editor window and also it removes the unselected tags and lists.
One thing: after removal, the cursor gets reset to the start of the line.

Implemented tag and list removing in task editor window

---

src/main/java/nl/mpcjanssen/simpletask/CalendarSync.java
src/main/res/values/strings.xml
src/main/res/xml/preferences.xml

I have:
- switched to all-day events, finally
- clarified the settings a little bit (at least I hope so)

Small improvements in calendar sync

---

src/main/res/values-de/strings.xml

Updated German translation (Calender Sync).

---

src/main/java/nl/mpcjanssen/simpletask/CalendarSync.java
src/main/res/values-de/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values-it/strings.xml
src/main/res/values-ko/strings.xml
src/main/res/values/strings.xml

Fix for #324 , insofar as not crashing and displaying an error message instead can be considered a fix...
@twckr mind checking my german for me one more time? :)

Calendar sync: Calendar manipulation error handling, fixes #324

---

src/main/res/values-de/strings.xml

Just added a few missing translations. Should be complete right now.

Completion of German Translation.

---

src/cloudless/res/values-pl/strings.xml
src/main/res/values-pl/strings.xml

As I promised I have created Polish translation for Simpletask. Enjoy ;)

Polish translation

---

src/main/res/layout/lua_config.xml

I think we could benefit by moving actions to the app bar for more space, but I can do that separately.

add scrollbar in lua config. fixes #522

---

src/main/java/nl/mpcjanssen/simpletask/task/Task.kt
src/main/java/nl/mpcjanssen/simpletask/util/Util.kt

Fixing #445

---

src/main/res/menu/main.xml

Put menu items in order of importance/use frequency

reorder main menu

---

src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt

Also some (related) continued refactoring. Isn't it pretty?

Show back arrow on selection. Fixes #535.

---

src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt

Remove last references to left or right drawers

---

src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt

It was a two line function that's only called in one place

Combine hideSelectionToolbar into onCreateOptionsMenu

---

src/main/res/menu/main.xml

It feels wrong not to have lua next to settings in the menu.

one last tweak to menu ordering

---

src/main/AndroidManifest.xml
src/main/java/nl/mpcjanssen/simpletask/AddTask.kt
src/main/java/nl/mpcjanssen/simpletask/FilterActivity.kt
src/main/java/nl/mpcjanssen/simpletask/HelpScreen.kt
src/main/java/nl/mpcjanssen/simpletask/LuaConfigScreen.kt
src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt
src/main/java/nl/mpcjanssen/simpletask/ThemedActivity.kt
src/main/java/nl/mpcjanssen/simpletask/ThemedPreferenceActivity.kt
src/main/java/nl/mpcjanssen/simpletask/task/Task.kt
src/main/java/nl/mpcjanssen/simpletask/util/Config.kt
src/main/java/nl/mpcjanssen/simpletask/util/Util.kt
src/main/res/layout/add_task.xml
src/main/res/layout/filter.xml
src/main/res/layout/history.xml
src/main/res/layout/log.xml
src/main/res/layout/lua_config.xml
src/main/res/layout/main.xml
src/main/res/layout/main_landscape.xml
src/main/res/values/colors.xml
src/main/res/values/dimens.xml
src/main/res/values/styles.xml
src/main/res/values/themes.xml

I did the thing and updated the color scheme the way I'd like it. I drew a lot of inspiration from Signal-android. There are still a bunch of rough edges (updating the status bar color on selection, making selected elements in the settings brighter, and a few other odds and ends) but the core is in place.
There's a bunch of issues this closes: ~~that I'm way too tired to find right now.~~
#597 #589 #536, maybe a few others
Still todo:
~~- I don't like the look of the current half-blue, half-gray on selection color scheme.~~
- ~~I'd like to think more about what I would like more.~~
- ~~Color is really important to app identity; we don't want to keep changing it up.~~
- ~~We should do all all color changes at the same time.~~
- ~~It's been a while since we pushed to stable and I don't like …

PRETTY COLORS++

---

src/main/java/nl/mpcjanssen/simpletask/HelpScreen.kt
src/main/java/nl/mpcjanssen/simpletask/util/Config.kt
src/main/res/layout/appwidget.xml
src/main/res/layout/appwidget_dark.xml
src/main/res/layout/filter.xml
src/main/res/layout/help.xml
src/main/res/values/strings.xml
src/main/res/values/styles.xml
src/main/res/values/themes.xml

#608 broke the background color for the overflow icon.

fix addtask and overflow menu styling

---

build.gradle
extras/simpletask-key/build.gradle

update to gradle v2.2.0

---

src/main/java/nl/mpcjanssen/simpletask/CalendarSync.kt
src/main/java/nl/mpcjanssen/simpletask/Preferences.kt
src/main/java/nl/mpcjanssen/simpletask/util/Config.kt
src/main/res/values/strings.xml
src/main/res/xml/calendar_preferences.xml
src/main/res/xml/interface_preferences.xml
src/main/res/xml/preference_headers.xml

reverts 44cbcd5 (amongst others)

revert threshold reminder removal

---

src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt

leave quick filter drawer open on item selection

---

src/main/res/xml-v21/interface_preferences.xml
src/main/res/xml/calendar_preferences.xml

Forgot to remove this part earlier

fully restore threshold date functionality

---

src/main/res/layout/add_task.xml
src/main/res/layout/appwidget.xml
src/main/res/layout/appwidget_dark.xml
src/main/res/layout/history.xml
src/main/res/layout/keep_dialog_item.xml
src/main/res/layout/list_header.xml
src/main/res/layout/list_item.xml
src/main/res/layout/log.xml
src/main/res/layout/log_item.xml
src/main/res/layout/login.xml
src/main/res/layout/logintoodledo.xml
src/main/res/layout/lua_config.xml
src/main/res/layout/multi_filter.xml
src/main/res/layout/seek_bar_preference.xml
src/main/res/layout/simple_list_item_multiple_choice.xml
src/main/res/layout/simple_list_item_single_choice.xml
src/main/res/layout/single_filter.xml
src/main/res/layout/sort_list_item.xml
src/main/res/layout/widget_list_item.xml
src/main/res/layout/widget_simple_list_item.xml

Changed my mind about doing this in one commit vs as I edit xml files.

change fill_parent (deprecated) to match_parent

---

src/main/java/nl/mpcjanssen/simpletask/task/ByContextFilter.kt
src/main/java/nl/mpcjanssen/simpletask/task/ByPriorityFilter.kt
src/main/java/nl/mpcjanssen/simpletask/task/ByProjectFilter.kt

I wanted to see what they did and kotlin is way easier to read than java. And at that point, why not just make a MR?

convert filters to kotlin

---

src/main/AndroidManifest.xml

Indentation was wonky, and it didn't follow the conventions in our other xml files.

AndroidManifest.xml whitespace changes

---

src/main/res/values/strings.xml

I should probably check if I can just push this via weblate. But this is easier for now :P

clean up phrasing of Color preference

---

app/src/main/java/nl/mpcjanssen/simpletask/FilterActivity.kt
app/src/main/java/nl/mpcjanssen/simpletask/FilterScriptFragment.kt
app/src/main/java/nl/mpcjanssen/simpletask/LuaConfigScreen.kt
app/src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt
app/src/main/res/layout/script_filter.xml
app/src/main/res/menu/filter.xml
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml

Implements the fix suggested by @smichel17 for #723 .

Replace hard-coded translation strings with variables

---

app/src/main/assets/script.de.md
app/src/main/assets/script.en.md
app/src/main/java/nl/mpcjanssen/simpletask/FilterScriptFragment.kt
app/src/main/java/nl/mpcjanssen/simpletask/LuaInterpreter.kt
app/src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt
app/src/main/java/nl/mpcjanssen/simpletask/task/Task.kt
app/src/main/java/nl/mpcjanssen/simpletask/util/Util.kt

This adds 'onDisplay()' as a Lua function, similar to 'onGroup()'. If the feature or implementation is undesired, please let me know and I'll close this PR.
Place-holder text has been added to the script.de.md file because I do not know German.

Add onDisplay() feature.

---

app/src/main/res/layout/main.xml

If desired, this PR fixes https://github.com/mpcjanssen/simpletask-android/issues/712.

Move close button to right-side of screen.

---

app/src/main/java/nl/mpcjanssen/simpletask/ActiveFilter.kt

I think this fixes issue: https://github.com/mpcjanssen/simpletask-android/issues/739

If 'Invert filter' is active, do not include list or tag when creating a new task.

---

app/src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt

I know you normally don't like pure style changes, but this one was 160 chars long and was annoying to deal with when browsing the code on mobile. Merge or don't, as you wish :)
I didn't test to see if it builds or anything because I'm not on a machine with a dev environment set up, but unless I made a grave syntax error, shouldn't be any issues.

clean up long line

---

app/src/main/java/nl/mpcjanssen/simpletask/task/TodoList.kt

Did this from my phone using mgit as an experiment; haven't tested as a result. I'll do that when I get to a computer in a sec.

sort before filtering so scripts work as expected

---

app/src/main/java/nl/mpcjanssen/simpletask/Query.kt
app/src/main/java/nl/mpcjanssen/simpletask/task/ByContextFilter.kt
app/src/main/java/nl/mpcjanssen/simpletask/task/ByPriorityFilter.kt
app/src/main/java/nl/mpcjanssen/simpletask/task/ByProjectFilter.kt
app/src/main/java/nl/mpcjanssen/simpletask/task/ByTextFilter.kt

This is pure style/cleanup. It's the kind of thing I'd do in my own project; I know you prefer to do it only if there's functional changes as well, of which this PR has none. Thus, I will have no hard feelings if you reject this PR :)
WIP because it breaks some tests.

WIP: filter cleanup

---

app/src/main/java/nl/mpcjanssen/simpletask/FilterActivity.kt

I know you don't like non-functional changes, but I do, where they allow me to change `var`s to `val`s or enforce scope. Sooo… take it or leave it. It didn't take me long.

more idiomatic kotlin in FilterActivity

---

app/src/main/java/nl/mpcjanssen/simpletask/AddTask.kt
app/src/main/java/nl/mpcjanssen/simpletask/adapters/ItemDialogAdapter.kt
app/src/main/java/nl/mpcjanssen/simpletask/util/Util.kt

Done!
> **¡NOT ready to merge until I remove WIP from the title!**
> 
> There are still a bunch of rough edges to iron out (for example, handling duplicates). Also cleanup of comments and debug code. However, this is a functional preview of #183.
> 
> @mpcjanssen I am planning on force pushing to this branch; I just wanted to share a bit earlier :)

Dynamic Dialog

---

app/src/main/assets/index.en.md

Will work on EN and ES now and try to create a PR for all three files

Explanation for GTD abbreviation added (EN)

---

app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml

Change: Todo.txt removes priority on completion --> Simpletask keeps priority on completion
Linked to: #1149 and #1150 and #1151

keep_prio_summary adjusted (EN+DE)

---

app/build.gradle

Update dropbox-core-sdk to 5.2.0

---

app/src/main/java/nl/mpcjanssen/simpletask/task/DragTasksCallback.kt
app/src/main/java/nl/mpcjanssen/simpletask/task/TaskAdapter.kt

In response to https://github.com/mpcjanssen/simpletask-android/pull/1158#issuecomment-1100687559.  I also added some comments :)
(This PR is based on the modernize branch, not master.  It can be rebased without conflicts by doing `git checkout fix-drag-with-reverse-file-order; git rebase modernize --onto master`.)

Fix drag with reverse file order

---

README.md

Also added documentation header.
Intro text based on content of app/src/main/assets/index.en.md

Clarify todo.txt near top of file

---

defaulttasks.txt

This is a file 'defaulttasks.txt' to be loaded (by default?) for new users. It contains some general tasks, and some hints on 'hidden features'.
@smichel17 and colleagues feel free to move the file to a location (folder, path) of your gusto, and/or adjust (shorten) its contents.

initial defaulttasks.txt EN created for #911
