mpcjanssen/simpletask-android

src/main/AndroidManifest.xml, src/main/java/nl/mpcjanssen/simpletask/CalendarSync.java, src/main/java/nl/mpcjanssen/simpletask/Preferences.java, src/main/java/nl/mpcjanssen/simpletask/Simpletask.java, src/main/java/nl/mpcjanssen/simpletask/TodoApplication.java, src/main/res/values-de/strings.xml, src/main/res/values-it/strings.xml, src/main/res/values/donottranslate.xml, src/main/res/values/strings.xml, src/main/res/xml/preferences.xml
Basic (very imperfect) implementation of calendar due&threshold date sync.
I do not actually expect this PR to be merged, I created it because it's easier to see & talk about the code like this.
This is basically just a proof-of-concept imeplementation. There are a few issues right now:
+ requires API level 16 because of `Events.CUSTOM_APP_PACKAGE` (without that I don't know how to mark events belonging to Simpletask)
+ sync routine is rather slow, as it involves lookups of existing events, effectively making it O(n^2)
+ if a calendar is removed from the sync settings, its Simpletask events are not removed
+ if the reminders margin days number is changed, existing reminders are not altered
...and there's probably more. But the very basic functionality has been ok, at least on my device. …
=> Calendar due & threshold date sync

src/main/java/nl/mpcjanssen/simpletask/CalendarSync.java
I noticed `ScheduledThreadPoolExecutor` eats exceptions,
so I added code to redirect them into logcat. Just in case.
Low priority.
=> Calendar sync: Fix: Exceptions eaten by STPE

src/main/assets/MYN.es.md, src/main/assets/addtask.es.md, src/main/assets/defertasks.es.md, src/main/assets/design.es.md, src/main/assets/gradle.es.md, src/main/assets/index.es.md, src/main/assets/index.md, src/main/assets/intents.es.md, src/main/assets/listsandtags.es.md, src/main/assets/script.es.md, src/main/assets/ui.es.md, src/main/assets/versions.es.md, src/main/java/nl/mpcjanssen/simpletask/AddTask.java, src/main/java/nl/mpcjanssen/simpletask/HelpScreen.java, src/main/res/values-es/strings.xml, src/main/res/values/strings.xml
Dear Mark,
I was a bit surprised that you already had uploaded the strings.xml. Anyway, I translated the docs as well. To enable this I modified some of the code (java) files. I tried to stick to minimal modifications. A more general approach was possible but you are the one able to decide which is the best strategy for i8n.
For now: In strings.xml, a string can indicate which help file should be loaded. As the index help and the addtask help were "hardcoded" as constants, I had to superseed those with entries in strings.xml. The more general approach could be to use just the file name in the constants (without extension) and allow the language-specific tail to be added.
I hope that you like the solution. Let me know your thoughts.
Best,
Martin
=> Spanish translation

src/main/assets/index.en.md, src/main/assets/index.es.md
todo.txt-tools has been obsoleted by my other project, topydo. Change the links to the (same) description of the topydo project.
=> Link to the topydo project rather than the (obsoleted) todo.txt-tools.

src/main/java/nl/mpcjanssen/simpletask/Simpletask.java, src/main/res/values/donottranslate.xml, src/main/res/values/strings.xml, src/main/res/xml/preferences.xml
I would like to see this option in the app. Basically if the user selects one of the options, the task will be shortened to one line.
An example use case is when I have a long URL in the task text prefixed with a short summary, e.g.: "Learn about the Proxy deisgn pattern: http://verylongurl.com".
Please review and consider pulling.
=> Implemented ellipsizing support for task texts

src/main/java/nl/mpcjanssen/simpletask/CalendarSync.java, src/main/res/values-de/strings.xml, src/main/res/values-es/strings.xml, src/main/res/values-it/strings.xml, src/main/res/values-ko/strings.xml, src/main/res/values/strings.xml
It makes calendar view unnecessarily messy, I don't know why I did this in the first place...
=> Calendar sync: Don't prefix event titles any more

src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt, src/main/res/layout/drawer_list_item.xml, src/main/res/layout/drawer_list_item_checked.xml, src/main/res/layout/main.xml
When using light theme, the drawer background stays dark. To fix this I changed to use the colors from current theme in the drawer background and text.
=> Fix drawers background to match current theme

src/main/res/layout/appwidget.xml
Accidentally removed in #537. Removing it had no visible effect on the emulated nexus 5x running android N, but let's not find out if it breaks something else right now.
=> revert unintended change

build.gradle
There's a build error about a conflicting provider. I'm not sure exactly how to solve that.
Should also change the icon (suggestion: recolor it) and/or app name (suggestion: "Simpletask-DEBUG" for debug builds).
I wasn't sure how to do that since the project structure isn't the default, so there isn't a folder where I can put resources for debug builds. That I know of, anyway.
=> WIP: Debug builds

src/main/java/nl/mpcjanssen/simpletask/AddTask.kt, src/main/java/nl/mpcjanssen/simpletask/Constants.kt, src/main/java/nl/mpcjanssen/simpletask/FilterActivity.kt, src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt, src/main/java/nl/mpcjanssen/simpletask/task/TodoList.kt
Turns out when the active filter was changed, it wasn't loading with `showSelected = true`. Now it does.
=> always show selected tasks in the filter. fixes #627

src/main/java/nl/mpcjanssen/simpletask/AppWidgetService.kt, src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt, src/main/java/nl/mpcjanssen/simpletask/util/Util.kt, src/main/res/layout/main.xml, src/main/res/values/colors.xml
Use colors defined from `colors.xml` rather than `android.R.color.holo_something`. So far all the colors are the exact same as before, this just frees us to change them later if we desire.
Then fix due dates so `due:tomorrow` shows again and color `due:tomorrow` light blue.
=> soft code colors and add due:tomorrow

src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt
We're kind of abusing setFilteredTasks, which updates the entire list. I remember reading about a way to notify of only the task in question that changed. But of course now I can't find that documentation, so let's stick with this for now :P
=> refilter tasks when unselecting for #627

app/src/main/java/nl/mpcjanssen/simpletask/CalendarSync.kt
Finally got around to finish the diffing implementation.
Hopefully this way reminders should sync much more efficiently.
One thing I'm still a bit uncertain about is what the `SYNC_DELAY_MS` should be.
It used to be 1s, which is way too little. I set it to 20s in this patch, which means the sync would
be performed once in 20s tops, which also means that it'll take at least 20s before changes are apparent in the calendar. Hopefully that won't bother users.
Let me know if you have an opinion about that.
=> Calendar sync: Implement diffing and increase sync timeout

MYN.de.md, MYN.en.md, addtask.de.md, addtask.en.md, extensions.de.md, extensions.en.md, index.de.md, index.en.md, intents.de.md, intents.en.md, listsandtags.de.md, listsandtags.en.md
@mpcjanssen Finally I finished the german translation of the help-files. You were right, it was quite some work :-)
The following files I didn't translate, because they are not linked to the help index and I am not sure, if they are still in use: 
**defertasks, design, gradle** and **versions**. The **changelog** I didn't translate neither, doesn't make sense.
I wrote some comments directly into the files and marked them with **???** so they can easily be searched for.
Comments or questions to some help files:
**addtasks**: headers without text, is there missing something? I deleted them for now or did you plan to add something? 
**extensions**: I suggest to separate the section on the todo.txt-extensions from addtasks and index and put it into a new file. This way the text is only kept …
=> WIP - Help files, German translation

app/src/main/java/nl/mpcjanssen/simpletask/Preferences.kt
Update font size when custom value is changed for #756
Request calendar permission when sync threshold is enabled
=> Correctly respond when font size and sync threshold change

app/src/main/java/nl/mpcjanssen/simpletask/AddTask.kt
When using the add task widget, nothing syncs before trying to add, leading to easily avoidable conflicts.
=> Sync TodoList on adding tasks

app/src/main/java/nl/mpcjanssen/simpletask/FilterOtherFragment.java
I think this fixes this: https://github.com/mpcjanssen/simpletask-android/issues/644
=> Ensure "Create is threshold" remains checked after switching away from page.

app/src/main/java/nl/mpcjanssen/simpletask/AddTask.kt, app/src/main/java/nl/mpcjanssen/simpletask/task/TodoList.kt
I noticed a new bug with the latest builds. Perhaps it has already been fixed. If not, this illustrates it and offers a possible fix.
To reproduce:
Create one or more tasks. No need to add lists or tags.
Select the task(s).
Click the pencil icon to edit the task(s)
Change the text of one or more tasks.
Click the save button.
The text of the tasks that were edited are not updated with the new values.
This PR tries to make minimal changes to the code to highlight and fix the problem. The changes may not be the desired method of fixing this bug. I will not be offended at all if this PR is rejected.
Notes:
While editing, tasks are listed in the order they are selected, not the currently displayed sort order.
While editing, any task can be deleted by removing all text on the line and leaving …
=> Allow text of tasks to be updated.

app/src/main/java/nl/mpcjanssen/simpletask/LuaConfigScreen.kt
Right now we save the imported config immediately. I think if the user chooses to import but then presses the X to discard, they'd expect to revert to the previous state, not the imported one.
=> let the user decide whether to save imported lua config

app/src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt
`ActiveFilter.prefill` already prefixes a space, so we don't need to do it again here.
=> fix duplicate space when adding task with prefill

app/src/main/java/nl/mpcjanssen/simpletask/LuaInterpreter.kt
When indexing by zero, some standard library features like `ipairs(table)` will skip the first element in the table-as-an-array.
This will break people's scripts if they use this, so that's a pain, but so is not being able to properly iterate through the tokens.
=> index tokens by 1 to follow lua convention

app/src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt
If the lua onDisplay callback is defined, share that text (ie, as
displayed in the app) instead of the full text as in the config file.
Same for creating calendar appointments.
---
Ideally, we'd share the task text as it is displayed (see #236). However, there is currently no concept of that in the code. Adding the functionality without refactoring to create the concept in the code would be a *ton* of duplicate code.
I don't want to create that much tech debt, but at the same time, I don't have enough time on my hands to do the needed refactoring. So, this is a compromise: Do the intuitive thing iff the lua onDisplay callback is defined (since an abstraction of that already exists, it's only a few lines to implement).
=> share visible text if using lua onDisplay

app/src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt
All of these are related to use of null in one way or another. Most were trying to eliminate non-null assertions (`!!`) and clarify confusing code.
I know you're generally opposed to purely cosmetic changes because they screw up git blame. For this reason, I did not attempt to "fix" all non-idiomatic code. Instead, I restricted myself to places where there are tangible benefits, which I will point out inline with a review of this PR.
There's a couple that I'm not sure are *actually* less confusing / better in this style; I'll point them out in the review and am happy to them if you'd like.
=> more idiomatic kotlin, esp. w/ nulls

app/src/main/java/nl/mpcjanssen/simpletask/AddTask.kt, app/src/main/java/nl/mpcjanssen/simpletask/FilterActivity.kt, app/src/main/java/nl/mpcjanssen/simpletask/FilterSortFragment.kt, app/src/main/java/nl/mpcjanssen/simpletask/MainFilter.kt, app/src/main/java/nl/mpcjanssen/simpletask/Query.kt, app/src/main/java/nl/mpcjanssen/simpletask/SavedQuery.kt, app/src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt, app/src/main/java/nl/mpcjanssen/simpletask/adapters/ItemDialogAdapter.kt, app/src/main/java/nl/mpcjanssen/simpletask/util/Util.kt
This PR aims to add the concept of an active query. That means:
=> Persistence

app/src/main/java/nl/mpcjanssen/simpletask/AppWidgetService.kt, app/src/main/java/nl/mpcjanssen/simpletask/MultiComparator.kt, app/src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt, app/src/main/java/nl/mpcjanssen/simpletask/task/Priority.kt, app/src/main/java/nl/mpcjanssen/simpletask/task/Task.kt
Refactor to remove unused code, and take advantage of stuff kotlin gives us in enums.
Bugfix: Currently, if you select multiple tasks with Priority A and try
to change their priority, the dialog will be pre-filled with '-' as
their priority. This makes it so 'A' will be pre-filled. If the tasks
have different priorities, the pre-fill will still be '-'.
=> Refactor Priority.kt and prio dialog bugfix

app/src/main/java/nl/mpcjanssen/simpletask/AddTask.kt, app/src/main/java/nl/mpcjanssen/simpletask/AppWidgetService.kt, app/src/main/java/nl/mpcjanssen/simpletask/FilterActivity.kt, app/src/main/java/nl/mpcjanssen/simpletask/MyAppWidgetProvider.java, app/src/main/java/nl/mpcjanssen/simpletask/Query.kt, app/src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt, app/src/main/java/nl/mpcjanssen/simpletask/util/Config.kt
This is just a bit of code cleanup. I…
- Made `initFromJSON`, `initFromPrefs`, and `initFromIntent` private
- Added constructors which take a `jsonObject`, `sharedPreferences`, or `intent` and call the respective `initFrom`
- Fixed compilation errors
This is a step towards eliminating state from queries, which we could eventually change to be a simple, immutable `data class`. It also makes it impossible to create bugs where we use a query before it's initialized.
Granted, it also removes the flexibility to initialize a query after it's created, but we're currently not doing that anywhere, and it's easy enough to make the `initFrom` functions public again if we need them later.
=> always initialize queries in the constructor

.github/workflows/ci.yml
I am in the process of deprecating setup-android as GitHub Actions now ships default containers with everything that's needed.
﻿
=> Switch away from deprecated setup-android

app/src/main/java/nl/mpcjanssen/simpletask/task/Task.kt
I added a function to remove trailing WhiteSpaceTokens when constructing a Task. This fixes #1103.
=> remove trailing WhiteSpaceToken when constructing a Task

app/src/main/assets/index.de.md
DE + EN fine now. ES already contained explanations.
=> Explanation for GTD abbreviation added (DE)

app/src/main/java/nl/mpcjanssen/simpletask/MultiComparator.kt, app/src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt, app/src/main/java/nl/mpcjanssen/simpletask/task/DragTasksCallback.kt, app/src/main/java/nl/mpcjanssen/simpletask/task/TaskAdapter.kt, app/src/main/java/nl/mpcjanssen/simpletask/task/TodoList.kt, app/src/main/res/layout/list_item.xml
What this does:
* Allows reordering tasks that are otherwise unsorted (i.e. in the file order).  To see any effects of this feature, you first have to go into Filter -> Sort and move "File Order (unsorted)" above "Alphabetical".
* The drag&drop begins by touching the black square (see screenshot below).  The behavior of long press on a task is unchanged, it still opens an actions dialog if there is e.g. a link in the task, or does nothing if there's no actions.
* The black square is visible only for tasks that a) are selected and b) are sorted the same as other tasks.  (E.g. the top two tasks in the screenshot are sorted the same.  The third task cannot be dragged because there's no other task with priority (B) that it could be swapped with.)
Small usability features:
* We detect whether …
=> Allow reordering tasks by drag & drop

app/build.gradle
Hi @mpcjanssen!
Back in 2020, I was having some trouble with a `stream was reset: NO_ERROR` error that was fixed by using `okhttp` version `4.10.0-RC1`. https://github.com/mpcjanssen/simpletask-android/issues/1099
It looks like a change was made a year ago to 'not vendor Sardine' which reverted okhttp back to `4.9.0`, and reintroduced the error. https://github.com/mpcjanssen/simpletask-android/commit/e10108322734df2bb222e83874e78542fbaddb09
Would it be possible to flip to `4.10.0-RC1` again?
For some reason, `4.10.0` is not working but `5.0.0-alpha.10` is. If a `5.0.0` version is ever released, there would be some hope to not use a RC version. If you want, I could instead try to upgrade the `okhttp` version in `sardine-android`.
Thanks!
=> Use okhttp 4.10.0-RC1

app/src/nextcloud/java/nl/mpcjanssen/simpletask/remote/FileStore.kt
Fixes the circleci error caused by my pull request #1225.
Sorry, I'm new to Kotlin ...
I used `lowercase()` because Android Studio marked `toLowerCase()` as deprecated.
`lowercase()` is not experimental since Kotlin 1.5 - but the project uses 1.4.32.
=> Fix circleci error
